### ISSUE TITLE
Замечания по Product Vision и User Stories

### ISSUE THREAD

**Issue by nvamelichev** [elevankoff/roguelike#1]
В целом: очень нравится, что получилось :+1: 

Мелкие замечания:
- [ ] В Product Vision я бы "почему проект может быть успешен" и "риски" начал с красной строки (с нового абзаца)
- [x] User Stories 2.1) это не совсем пользовательские истории, это описание категорий пользователей и описание геймплея. Предлагаю это переместить в Product Vision, а даже лучше - завести два дополнительных раздела ("Пользователи проекта" и "Геймплей") между Product Vision и User Stories, и перетащить контент из пункта 2.1 туда :-)
- [x] User Stories 2.5) это интересно, обычно в roguelike-играх сохранёнок нет, но поскольку ваш проект ориентирован на казуальных а не хардкорных игроков - это хорошо и оправданно, и наверное стоит эту User Story сделать НЕ опциональной.

**Comment by AndrewKoz** [comment]
Сделано!
