### ISSUE TITLE
Окончательные замечания по User Stories

### ISSUE THREAD

**Issue by nvamelichev** [elevankoff/roguelike#2]
- [ ] User Stories 2.1) и 2.2) предлагаю объединить в одну историю (про короткую игру)
- [ ] В User Story про сохранение игры нужно пояснить, что имеется в виду вариант длительной паузы игры (прервать игру и вернуться), и после смерти в игре с помощью неё восстановиться нельзя (т.к. это противоречит принципам жанра roguelike)
- [ ] Предлагаю указать, что Bullet hell - опциональная фича. Получится - хорошо, не получится - всё равно будет интересная игра :-)

**Comment by AndrewKoz** [comment]
Сделано!
