### ISSUE TITLE
Замечания по CRC-карточкам и UML

### ISSUE THREAD

**Issue by nvamelichev** [elevankoff/roguelike#3]
- [x] Хранить данные - это не ответственность (=метод) класса, только если это не класс репозитория/структуры данных/кэша/таблицы базы данных или чего-то подобного. Лучше существенные атрибуты класса описать на обратной стороне CRC-карточки.
- [x] Инвентарь - предлагается сделать отдельный класс для хранения ограниченного количества Item. Будет композирован в Player, будет агрегировать Item'ы.
- [x] У класса Player - агрегация с локацией, а не композиция, т.к. игрок - не неотъемлемая часть локации. (А вот монстры - неотъемлемая, в нашем случае :-))
- [x] Жду UML-диаграмму, описывающую поведение системы. Поскольку вы решили заюзать фреймворк с игровым циклом, наверное уместна будет Sequence Diagram

**Comment by AndrewKoz** [comment]
С UML-диаграммой описывающей поведение системы некоторые проблемы: мы пока плохо представляем как именно будет выглядеть код на LibGDX, поэтому сложно составить сколь-нибудь точную диаграмму происходящего. 
Я думаю, что стоит написать первый рабочий прототип и по нему уже будет видно как строить диаграмму

**Comment by nvamelichev** [comment]
> мы пока плохо представляем как именно будет выглядеть код на LibGDX, поэтому сложно составить сколь-нибудь точную диаграмму происходящего.

А если исключить из рассмотрения LibGDX и рассмотреть только ваш код? Можете ли вы нарисовать, например, Sequence Diagram для какого-нибудь типичного игрового взаимодействия? Просто чтобы понять, как придуманные вами классы с Class Diagram между собой взаимодействуют для реализации какой-нибудь простой пользовательской истории :-)
